CREATE TABLE if not exists actions (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    actions VARCHAR(16),
    time TIMESTAMP
);

CREATE TABLE similarity (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    result FLOAT,
    time TIMESTAMP
);

