-- V1__Initial_schema.sql
CREATE TABLE IF NOT EXISTS actions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    action VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_actions_user_id ON actions(user_id);
CREATE INDEX IF NOT EXISTS idx_actions_event_id ON actions(event_id);
CREATE INDEX IF NOT EXISTS idx_actions_created_at ON actions(created_at);

CREATE TABLE IF NOT EXISTS similarities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id_a INT NOT NULL,
    event_id_b INT NOT NULL,
    similarity_score FLOAT NOT NULL,
    calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_similarities_event_a ON similarities(event_id_a);
CREATE INDEX IF NOT EXISTS idx_similarities_event_b ON similarities(event_id_b);