spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # User
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        #category
        - id: event_service_category_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**, /categories/**

        #compilation
        - id: event_service_compilation_route
          uri: lb://event-service
          predicates:
            - Path=/compilations/**, /admin/compilations/**

        #event
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/{userId}/events, /users/{userId}/events/{eventId}, /events/**

        #request
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests, /users/{userId}/requests/**, /requests/**

          #subscription
        - id: subscription_service_route
          uri: lb://subscription-service
          predicates:
            - Path=/users/{userId}/subscriptions/**

