spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://request-db:5432/ewm-request
    username: root
    password: root
  sql:
    init:
      mode: always

  stat-server:
    uri: http://stats-server:9090