spring:
  jpa:
    hibernate:
      ddl-auto: update  # создаёт/обновляет таблицы
    show-sql: true      # для отладки
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://request-db:5432/ewm-request
    username: root
    password: root

  stat-server:
    uri: http://stats-server:9090