spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://subscription-db:5432/ewm-subscription
    username: root
    password: root
  sql:
    init:
      mode: always

  stat-server:
    uri: http://stats-server:9090