stat-server:
  uri: http://localhost:9090

grpc:

  client:
    collector:
      discovery:
        enabled: true
      serviceId: collector
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

  analyzer:
    discovery:
      enabled: true
    serviceId: analyzer
    address: discovery:///analyzer
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext
